spring.application.name=taskflow-api
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/taskflowdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true